language: cpp
sudo: required
compiler:
  - clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq packaging-dev python3 python ninja
env:
  global:
    - UTILIKIT_CONFIG_TYPE=linux_conservative
    - UTILIKIT_CONFIG_TYPE=debian_stretch
script:
  - travis_build.sh
os:
 - linux